### ISSUE TITLE
Setup Todo

### ISSUE THREAD

**Issue by m1sk9** [approvers/domain#1]
```[tasklist]
### Tasks
- [x] Google Domains から Cloudflare Register への移管
- [x] Terraform で DNS record を管理できるようにする
- [x] DNS record の移行
```
